#!/bin/sh

DRIVENAME="$(grep ^drive-name /mnt/data/config/script.conf | cut -d= -f2-)"

# Run rclone
htpasswd -csb /workdir/htpasswd_webdav ${GLOBAL_USER} ${GLOBAL_PASSWORD}
exec 2>&1
exec rclone serve webdav ${DRIVENAME}:/ \
--htpasswd=/workdir/htpasswd_webdav \
--addr=localhost:61801 \
--buffer-size 4M \
--config /mnt/data/config/rclone.conf \
--use-mmap \
--vfs-cache-mode writes 