#!/bin/bash

sleep 60

DATE=$(date +%H%M | sed 's/^0//g')
while [ "${DATE}" != "${RESTART_TIME/:/}" ]; do
  sleep 10
done

DRIVE_NAME_AUTO="$(sed -n '1p' /mnt/data/config/rclone.conf | sed "s/\[//g" | sed "s/\]//g")"
if [ "${DRIVE_NAME}" = "auto" ]; then
  DRIVENAME=${DRIVE_NAME_AUTO}
else
  DRIVENAME=${DRIVE_NAME}
fi

rclone copy --config /mnt/data/config/rclone.conf /.aria2allinoneworkdir/aria2/aria2.session "${DRIVENAME}":/"${HEROKU_APP_NAME}"/

CONF=$(base64 /mnt/data/config/rclone.conf)
if [ "${HEROKU_API_KEY}" != "" ]; then
  curl -n -X PATCH https://api.heroku.com/apps/"${HEROKU_APP_NAME}"/config-vars \
  -d '{"RCLONE_CONFIG_BASE64": "'"${CONF}"'"}' \
  -H "Content-Type: application/json" \
  -H "Accept: application/vnd.heroku+json; version=3" -H "Authorization: Bearer "${HEROKU_API_KEY}""
fi
