#!/bin/sh

# Dummy run for building image
if [ "${MODE}" = "build" ]; then
       sleep infinity
fi

# Configure & run metube
python3 -m pip install -U yt-dlp &
DRIVENAME="$(grep ^drive-name /mnt/data/config/script.conf | cut -d= -f2-)"
rclone copy --config /mnt/data/config/rclone.conf "${DRIVENAME}":/"${HEROKU_APP_NAME}"/queue /.aria2allinoneworkdir/.metube/ 2>/dev/null
OUTPUT_TEMPLATE=${YTDL_OUTPUT_TEMPLATE}
cd /app
exec 2>&1
exec python3 /app/app/main.py