#!/bin/sh

# Dummy run for building image
if [ "${MODE}" = "build" ]; then
    sleep infinity
fi

# Configure filebrowser
DRIVE_NAME_AUTO="$(sed -n '1p' /mnt/data/config/rclone.conf | sed "s/\[//g" | sed "s/\]//g")"
if [ "${RCLONE_DRIVE_NAME}" = "auto" ]; then
    DRIVENAME=${DRIVE_NAME_AUTO}
else
    DRIVENAME=${RCLONE_DRIVE_NAME}
fi

rclone copy --config /mnt/data/config/rclone.conf "${DRIVENAME}":/"${HEROKU_APP_NAME}"/filebrowser.db /mnt/data/config/ 2>/dev/null

if [ ! -f "/mnt/data/config/filebrowser.db" ]; then
    filebrowser -d /mnt/data/config/filebrowser.db config init -r /mnt/data
    filebrowser -d /mnt/data/config/filebrowser.db users add ${GLOBAL_USER} ${GLOBAL_PASSWORD} --perm.admin --commands="sv,aria2c,rclone,du,df,free,nslookup,netstat,top,ps"
    if [ "${GLOBAL_LANGUAGE}" = "chs" ]; then
        filebrowser -d /mnt/data/config/filebrowser.db users update ${GLOBAL_USER} --locale zh-cn
    fi
else
    if [ "${GLOBAL_LANGUAGE}" = "chs" ]; then
        filebrowser -d /mnt/data/config/filebrowser.db users add ${GLOBAL_USER} ${GLOBAL_PASSWORD} --perm.admin --locale zh-cn --commands="sv,aria2c,rclone,du,df,free,nslookup,netstat,top,ps"
    else
        filebrowser -d /mnt/data/config/filebrowser.db users add ${GLOBAL_USER} ${GLOBAL_PASSWORD} --perm.admin --commands="sv,aria2c,rclone,du,df,free,nslookup,netstat,top,ps"
    fi
    filebrowser -d /mnt/data/config/filebrowser.db users update ${GLOBAL_USER} -p ${GLOBAL_PASSWORD}
fi

# Run filebrowser
exec 2>&1
exec filebrowser -d /mnt/data/config/filebrowser.db -b ${GLOBAL_PORTAL_PATH}/files -p 56801
