#!/bin/sh

# Dummy run for building image
if [ "${MODE}" = "build" ]; then
	sleep infinity
fi

# Run rclone
htpasswd -csb /.aria2allinoneworkdir/htpasswd ${GLOBAL_USER} ${GLOBAL_PASSWORD}
exec 2>&1
exec rclone rcd --rc-serve \
--rc-web-gui-no-open-browser \
--rc-htpasswd=/.aria2allinoneworkdir/htpasswd \
--rc-addr=localhost:56802 \
--buffer-size 4M \
--transfers 4 \
--config /mnt/data/config/rclone.conf \
--rc-allow-origin=* \
--use-mmap
