#!/bin/sh

# Dummy run for building image
if [ "${MODE}" = "build" ]; then
       sleep infinity
fi

# Configure aria2
touch /.aria2allinoneworkdir/aria2/aria2.session
DRIVENAME="$(grep ^drive-name /mnt/data/config/script.conf | cut -d= -f2-)"
rclone copy --config /mnt/data/config/rclone.conf "${DRIVENAME}":/"${HEROKU_APP_NAME}"/aria2.conf /mnt/data/config/ 2>/dev/null
rclone copy --config /mnt/data/config/rclone.conf "${DRIVENAME}":/"${HEROKU_APP_NAME}"/aria2.session /.aria2allinoneworkdir/aria2/ 2>/dev/null
rclone copy --config /mnt/data/config/rclone.conf "${DRIVENAME}":/"${HEROKU_APP_NAME}"/dht.dat /.aria2allinoneworkdir/aria2/ 2>/dev/null

if [ ! -f "/mnt/data/config/aria2.conf" ]; then
       cp /.aria2allinoneworkdir/aria2/aria2_${GLOBAL_LANGUAGE}.conf /mnt/data/config/aria2.conf
fi

/.aria2allinoneworkdir/aria2/tracker.sh /mnt/data/config/aria2.conf 2>/dev/null

if [ "${RCLONE_AUTO_MODE}" = "copy_remote_first" ]; then
       sed -i "s|^on-bt-download-complete=/.aria2allinoneworkdir/aria2/.*.sh|on-bt-download-complete=/.aria2allinoneworkdir/aria2/"${RCLONE_AUTO_MODE}".sh|g" /mnt/data/config/aria2.conf
       sed -i "s|^on-download-complete=/.aria2allinoneworkdir/aria2/.*.sh|on-download-complete=/.aria2allinoneworkdir/aria2/copy_remote_other.sh|g" /mnt/data/config/aria2.conf
elif [ "${RCLONE_AUTO_MODE}" = "dummy" ]; then
       sed -i "s|^on-bt-download-complete=/.aria2allinoneworkdir/aria2/.*.sh|on-bt-download-complete=/.aria2allinoneworkdir/aria2/clean.sh|g" /mnt/data/config/aria2.conf
       sed -i "s|^on-download-complete=/.aria2allinoneworkdir/aria2/.*.sh|on-download-complete=/.aria2allinoneworkdir/aria2/clean.sh|g" /mnt/data/config/aria2.conf
elif [ "${RCLONE_AUTO_MODE}" = "custom" ]; then
       :
else
       sed -i "s|^on-download-complete=/.aria2allinoneworkdir/aria2/.*.sh|on-download-complete=/.aria2allinoneworkdir/aria2/"${RCLONE_AUTO_MODE}".sh|g" /mnt/data/config/aria2.conf
       sed -i "s|^on-bt-download-complete=/.aria2allinoneworkdir/aria2/.*.sh|on-bt-download-complete=/.aria2allinoneworkdir/aria2/clean.sh|g" /mnt/data/config/aria2.conf
fi

# Run aria2
exec 2>&1
exec aria2c --conf-path="/mnt/data/config/aria2.conf" \
--enable-rpc \
--rpc-secret=${GLOBAL_PASSWORD} \
--rpc-listen-port=56800 \
--show-console-readout false \
--enable-mmap true
