#!/bin/bash

# Dummy run for building image
if [ "${MODE}" = "build" ]; then
  sleep infinity
fi

# Configure AriaNG
sed -i 's|rpcInterface:"jsonrpc"|rpcInterface:"'"${PORTAL_PATH/\//}"'/jsonrpc"|g' /.aria2allinoneworkdir/ariang/js/aria-ng-f1dd57abb9.min.js

# Configure homer
cp /.aria2allinoneworkdir/homer_conf/* /.aria2allinoneworkdir/homer/assets/tools/
cp /.aria2allinoneworkdir/homer_conf/homer_${LANGUAGE}.yml /.aria2allinoneworkdir/homer/assets/config.yml
sed -i "s|PORTAL_PATH|${PORTAL_PATH}|g;s|VMESS_PATH|${VMESS_PATH}|g;s|VMESS_UUID|${VMESS_UUID}|g" /.aria2allinoneworkdir/homer/assets/config.yml

# Run language script
/.aria2allinoneworkdir/caddy_init_${LANGUAGE}.sh

# Configure Caddyfile
HASH="$(caddy hash-password --plaintext ${PASSWORD})"
sed -i "s|HASH|${HASH}|g" /.aria2allinoneworkdir/Caddyfile

# Run caddy
exec 2>&1
exec caddy run --config /.aria2allinoneworkdir/Caddyfile --adapter caddyfile
